#!/bin/bash

_ARGS=$@

cmake \
  -D CMAKE_BUILD_TYPE=DEBUG \
  -D BUILD_SHARED_LIBS=ON \
  -D Trilinos_ENABLE_OpenMP=ON \
   \
  -D Trilinos_ENABLE_SEACAS=On \
  -D Trilinos_ENABLE_Tpetra=Off \
  -D Trilinos_ENABLE_Epetra=On \
  -D Trilinos_ENABLE_Anasazi=On \
  -D Trilinos_ENABLE_Intrepid=On \
  -D Trilinos_ENABLE_Shards=On \
  -D Trilinos_ENABLE_Teuchos=On \
  -D Trilinos_ENABLE_Belos=Off \
  -D Trilinos_ENABLE_STK="" \
  -D Trilinos_ENABLE_STKClassic=Off \
  -D Trilinos_ENABLE_STKUtil=On \
  -D Trilinos_ENABLE_STKTopology=On \
  -D Trilinos_ENABLE_STKMesh=On \
  -D Trilinos_ENABLE_STKIO=On \
  -D Trilinos_ENABLE_STKSearch=On \
  -D Trilinos_ENABLE_STKSearchUtil=On \
  -D Trilinos_ENABLE_STKTransfer=On \
  -D Trilinos_ENABLE_STKExprEval=On \
  -D Trilinos_ENABLE_STKDoc_tests=On \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
  -D Trilinos_DUMP_PACKAGE_DEPENDENCIES=Off \
  \
  -D Trilinos_ENABLE_TESTS=Off \
  -D Trilinos_ENABLE_STKIO_TESTS=Off \
  -D Trilinos_ENABLE_STKIO_EXAMPLES=Off \
  \
  -D Netcdf_LIBRARY_DIRS:PATH=/usr/lib \
  -D TPL_ENABLE_Netcdf:BOOL=ON \
  -D TPL_Netcdf_INCLUDE_DIRS:PATH=/usr/include \
  -D TPL_ENABLE_MPI=ON \
  -D MPI_BASE_DIR=/usr/ \
  -D MPI_BIN_DIR=/usr/bin \
  -D MPI_C_COMPILER:FILEPATH=/usr/bin/mpicc \
  -D MPI_CXX_COMPILER:FILEPATH=/usr/bin/mpic++ \
  -D MPI_Fortran_COMPILER:FILEPATH=/usr/bin/mpif77 \
  \
  -D CMAKE_INSTALL_PREFIX=./install \
  $EXTRA_ARGS \
  ../Trilinos

